# Every field of the config can be set directly or point to a env var by using $ keyword

# private key of the bot's wallet
key: $BOT_WALLET_PRIVATEKEY

# mnemonic phrase
mnemonic: $MNEMONIC

# number of excess wallets for submitting txs, requires mnemonic option
walletCount: $WALLET_COUNT

# topup amount for excess accounts, requires mnemonic option
topupAmount: $TOPUP_AMOUNT

# List of rpc urls
# for specifying more than 1 RPC in the env, separate them by a comma and a space
rpc: $RPC_URL

# List of write rpc urls for write transactions
# for specifying more than 1 RPC in the env, separate them by a comma and a space
writeRpc: $WRITE_RPC

# List of subgraph urls
# for more than 1 subgraphs, seperate them by comma and a space
subgraph: $SUBGRAPH

# arb contract address
arbAddress: $ARB_ADDRESS

# generic arb contract address
genericArbAddress: $GENERIC_ARB_ADDRESS

# dispair contract address
dispair: $DISPAIR

# list of liquidity providers names seperated by a comma for each
liquidityProviders: $LIQUIDITY_PROVIDERS

# Specifies the routing mode 'multi' or 'single' or 'full', default is 'single'
route: $ROUTE

# Seconds to wait between each arb round, default is 10
sleep: $SLEEP

# Option to specify time (in minutes) between pools updates, default is 0 minutes
poolUpdateInterval: $POOL_UPDATE_INTERVAL

# gas coverage percentage for each transaction to be considered profitable to be submitted
gasCoveragePercentage: $GAS_COVER

# Option to set a gas limit for all submitting txs optionally with appended percentage sign to apply as percentage to original gas
txGas: $TX_GAS

# Option to set a static gas limit for quote read calls, default is 1 milion
quoteGas: $QUOTE_GAS

# Minimum bot's wallet gas token balance before alering
botMinBalance: $BOT_MIN_BALANCE

# Option to multiply the gas price fetched from the rpc as percentage, default is 107, ie +7%
gasPriceMultiplier: $GAS_PRICE_MULTIPLIER

# Option to multiply the gas limit estimation from the rpc as percentage, default is 100, ie no change
gasLimitMultiplier: $GAS_LIMIT_MULTIPLIER

# Optional seconds to wait for the transaction to mine before disregarding it
timeout: $TIMEOUT

# number of hops of binary search, if left unspecified will be 1 by default
hops: $HOPS

# The amount of retries for the same order, max is 3, default is 1
retries: $RETRIES

# Option to maximize maxIORatio
maxRatio: $MAX_RATIO

# Only clear orders through RP4, excludes intra and inter orderbook clears
rpOnly: $RP_ONLY

# Specifies the owner limit
# for specifying in env use k=v form and separate by comma owner1=limit,owner2=limit,...
ownerProfile: $OWNER_PROFILE

# Specifies owned order to get funded once their vault goes below the specified threshold
# example for env: token|vaultId|threshold|toptupamount,token|vaultId|threshold|toptupamount,...
selfFundOrders: $SELF_FUND_ORDERS

# Filters for inc/exc orders, multiple items can be separated by a comma
sgFilter:
  # Only process these specific order hashes
  includeOrders: $INCLUDE_ORDERS

  # Does NOT process these specific order hashes
  excludeOrders: $EXCLUDE_ORDERS

  # Only process orders from these specific owners
  includeOwners: $INCLUDE_OWNERS

  # Does NOT process orders from these specific owners
  excludeOwners: $EXCLUDE_OWNERS

  # Only process orders from these specific orderbooks
  includeOrderbooks: $INCLUDE_ORDERBOOKS

  # Does NOT process orders from these specific orderbooks
  excludeOrderbooks: $EXCLUDE_ORDERBOOKS
