name: Docker image CI

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to give the build. Try to make it unique.'
        required: true

env:
  CHANNEL: ${{ inputs.tag || github.head_ref || github.ref_name }}
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  TAG_BASE: rainprotocol/arb-bot

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Nix 1/2
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - name: Install Nix 2/2
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Prepare Sushi Lib
        run: ./prep-sushi.sh

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build -t "$TAG_BASE:$CHANNEL" --build-arg GIT_SHA=${{ github.sha }} --build-arg DOCKER_CHANNEL=$CHANNEL .
      - run: |
          docker push "$TAG_BASE:$CHANNEL"